# Generated by Django 4.2.16 on 2024-10-24 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='ast',
            field=models.TextField(unique=True),
        ),
    ]
